- color: b60205
  description: Prevents production or dev due to perf, bug, build error, etc..
  name: blocking
- color: ee0701
  description: ""
  name: bug
- color: 0366d6
  description: Pull requests that update a dependency file
  name: dependencies
- color: c2e0c6
  description: Focuses on documentation changes
  name: docs
- color: 84b6eb
  description: ""
  name: enhancement
- color: a2eeef
  description: New addition or enhancement to existing solutions
  name: feature
- color: 7057ff
  description: Issues that are suitable for first-time contributors.
  name: good first issue
- color: 7057ff
  description: PR's that are suitable for first-time contributors to review.
  name: good first review
- color: 42f44e
  description: ❤ Has a reproduction in a codesandbox or single minimal repository
  name: has-reproduction
- color: 128A0C
  description: ""
  name: help wanted
- color: fbca04
  description: ""
  name: idea
- color: 006b75
  description: ""
  name: in progress
- color: 013f5b
  description: source of problem is not clear yet. the reproduction might help
  name: needs triage
- color: cc317c
  description: ""
  name: question
- color: 1d76db
  description: ""
  name: ready
- color: 621b8e
  description: ""
  name: waiting-for-answer
- color: ffffff
  description: ""
  name: wontfix
