sudo: true

language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    # cache node modules
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

notifications:
  # disable email notification
  email: false

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add coveralls
  # remove unused node modules from cache
  - npm prune

install: yarn

script: yarn test

after_script:
  # send code-coverage report to coveralls
  - coveralls < ./coverage/lcov.info || true
