[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "node ./scripts/netlify-check.js 'yarn build' && gatsby build --prefix-paths && mkdir -p docs/angular && mv public/* docs/angular && mv docs public/ && mv public/docs/angular/_redirects public"
[build.environment]
  NPM_VERSION = "6"
