name: release
on:
  push:
    branches:
      - master

jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      createGithubReleases: true
      releaseScript: release
      nodeVersion: 16
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
